copy tag containers to local scope to avoid temporaries
test/test_integration_tracer.cxx:255:3: note: Same iterator is used with containers 'span->int_tags()' that are temporaries or defined in different scopes.
  REQUIRE(span->int_tags().find("couchbase.retries") != span->int_tags().end());
  ^
test/test_integration_tracer.cxx:342:3: error: Same iterator is used with containers 'span->int_tags()' that are temporaries or defined in different scopes. [iterators3]
  REQUIRE(span->int_tags().find("couchbase.retries") != span->int_tags().end());